// packages/solid/src/native-component.ts
import { omit, type Element as SolidElement, type Ref } from "solid-js";
import { sendNativeCommand } from "@nativedesktop/core";
import type { JSX, NdNodeRef } from "./generated/intrinsics.ts";
import { applyRef, createElement, mergeProps, ref, spread, type SolidNode } from "./renderer.ts";

export interface NativeComponentOptions {
  /** Factory key registered by the app's platform-native library. */
  viewKind: string;
}

/// Host-level props (placement, styling, identity) forwarded verbatim to the
/// underlying <nativeview> intrinsic, derived from the generated intrinsic so
/// codegen additions flow through without edits here.
type NativeViewHostProps = Omit<JSX.IntrinsicElements["nativeview"], "viewKind" | "props" | "onNativeEvent" | "ref" | "children">;

export interface NativeComponentProps<Props, Event = unknown, Command = unknown> extends NativeViewHostProps {
  props: Props;
  onNativeEvent?: (event: { name: string; data: Event }) => void;
  ref?: Ref<NativeComponentRef<Command>>;
}

export interface NativeComponentRef<Command = unknown> extends NdNodeRef<"nativeview"> {
  send(command: string, arg?: Command): void;
}

/**
 * Defines a typed Solid component backed by an app-owned GTK/AppKit native view.
 * Props cross the stable NativeView ABI as JSON; events and commands use the
 * generic channel, so app components never require edits to widgets.json.
 */
export function defineNativeComponent<Props extends object, Event = unknown, Command = unknown>(
  options: NativeComponentOptions,
): (props: NativeComponentProps<Props, Event, Command>) => SolidElement {
  // Plain .ts rather than JSX, so an app built ahead of time (build.ts) never
  // loads babel at startup. This is the shape babel-preset-solid emits for a
  // spread intrinsic.
  return function NativeComponent(p) {
    const host: NativeViewHostProps = omit(p, "props", "onNativeEvent", "ref");
    const el = createElement("nativeview");
    ref(
      () => (node: SolidNode) => {
        // applyRef is typed for the renderer's own nodes; it accepts any ref value.
        if (p.ref) (applyRef as (ref: unknown, value: unknown) => void)(p.ref, makeRef<Command>(node));
      },
      el,
    );
    spread(
      el,
      mergeProps(host, {
        get viewKind() {
          return options.viewKind;
        },
        get props() {
          return JSON.stringify(p.props);
        },
        get onNativeEvent() {
          const handler = p.onNativeEvent;
          return handler
            ? (event: { nativeName?: string; data?: unknown }) => handler({ name: event.nativeName ?? "", data: event.data as Event })
            : undefined;
        },
      }) as object,
      false,
    );
    return el as unknown as SolidElement;
  };
}

// The node keeps its identity across a remount but takes a fresh wire id,
// so the wrapper reads the id live rather than copying it.
function makeRef<Command>(node: SolidNode): NativeComponentRef<Command> {
  const wrapper: NativeComponentRef<Command> = {
    get id() {
      return node.id;
    },
    type: "nativeview",
    send(command: string, arg?: Command) {
      sendNativeCommand(wrapper, command, arg);
    },
  };
  return wrapper;
}

// packages/react/src/native-component.ts
import { forwardRef, useCallback } from "./dev-react.ts";
import { createElement, type Ref } from "react";
import type { JSX, NdNodeRef } from "./generated/intrinsics.ts";
import type { Instance } from "./host-config.ts";
import { sendNativeCommand } from "@nativedesktop/core";

export interface NativeComponentOptions {
  /** Factory key registered by the app's platform-native library. */
  viewKind: string;
}

/// Host-level props (placement, styling, identity) forwarded verbatim to the
/// underlying <nativeview> intrinsic. Derived from the generated intrinsic —
/// minus the props defineNativeComponent manages itself — so codegen
/// additions (new slots, placement props) flow through without edits here.
type NativeViewHostProps = Omit<
  JSX.IntrinsicElements["nativeview"],
  "viewKind" | "props" | "onNativeEvent" | "ref" | "children"
>;

export interface NativeComponentProps<Props, Event = unknown> extends NativeViewHostProps {
  props: Props;
  onNativeEvent?: (event: { name: string; data: Event }) => void;
}

export interface NativeComponentRef<Command = unknown> extends NdNodeRef<"nativeview"> {
  send(command: string, arg?: Command): void;
}

/**
 * Defines a typed React component backed by an app-owned GTK/AppKit native view.
 * Props cross the stable NativeView ABI as JSON; events and commands use the
 * generic channel, so app components never require edits to widgets.json.
 */
export function defineNativeComponent<Props extends object, Event = unknown, Command = unknown>(
  options: NativeComponentOptions,
) {
  return forwardRef<NativeComponentRef<Command>, NativeComponentProps<Props, Event>>(function NativeComponent(componentProps, ref) {
    const { props, onNativeEvent, ...hostProps } = componentProps;
    // Stable across re-renders: a fresh callback ref would make the
    // reconciler detach (ref(null)) and reattach on every committed update.
    const setRef = useCallback((instance: Instance | null) => {
      if (typeof ref === "function") {
        ref(instance ? makeRef<Command>(instance) : null);
      } else if (ref) {
        (ref as { current: NativeComponentRef<Command> | null }).current = instance ? makeRef<Command>(instance) : null;
      }
    }, [ref]);
    return createElement("nativeview", {
      ...hostProps,
      viewKind: options.viewKind,
      props: JSON.stringify(props),
      onNativeEvent: onNativeEvent
        ? (event: { nativeName?: string; data?: Event }) => onNativeEvent({ name: event.nativeName ?? "", data: event.data as Event })
        : undefined,
      ref: setRef as Ref<NdNodeRef<"nativeview">>,
    });
  });
}

// One wrapper per instance, so ref consumers see a stable object identity
// for the lifetime of the underlying native view.
const refCache = new WeakMap<Instance, NativeComponentRef<unknown>>();

function makeRef<Command>(instance: Instance): NativeComponentRef<Command> {
  let wrapper = refCache.get(instance);
  if (!wrapper) {
    wrapper = {
      id: instance.id,
      type: "nativeview",
      send(command: string, arg?: unknown) {
        sendNativeCommand({ id: instance.id, type: "nativeview" }, command, arg);
      },
    };
    refCache.set(instance, wrapper);
  }
  return wrapper as NativeComponentRef<Command>;
}
